### ISSUE TITLE
Upgrading to EE 2.3x gives error

### ISSUE THREAD

**Issue by johndwells** [focuslabllc/dev_docs.ee_addon#1]
I've seen this now on 3 different setups using Dev Docs, happens when upgrading EE2.2.2 to EE2.3, and EE2.3 to EE2.3.1:

An Error Was Encountered
Unable to locate the model you have specified: dev_docs_setup_model

Not sure what's causing it, would help debug but I'm mad up against it....

Cheers,
John

**Comment by lincolnpixel** [comment]
same problem here, any help?

Cheers

**Comment by erikreagan** [comment]
Thanks for the report. Sorry for the delayed response. I didn't have a notification for the issue. 

I'll take a look at this and see what's up. Perhaps a missing add_package_path().

**Comment by erikreagan** [comment]
Hey guys

I'm not done investigating the problem yet, but I have a temporary patch if you're interested. It seems that the `add_package_path()` method isn't doing what it's supposed to during the install wizard.

I'll continue to dig around and see if this is an issue with my add-on or with EE in general. When applying the patch below I started seeing CI error messages from other 3rd party add-ons, so I suspect it's EE and not me.

Until I get a final solution, open `third_party/dev_docs/upd.dev_docs.php` and look for [line 39](https://github.com/focuslabllc/dev_docs.ee_addon/blob/master/dev_docs/upd.dev_docs.php#L39) and replace it with the following:

`$this->_EE->load->add_package_path(APPPATH . '../expressionengine/third_party/dev_docs');`

**Comment by erikreagan** [comment]
This has been confirmed (privately at this point) as an EE bug and not a bug within the add-on itself. I'm filing a specific bug report soon, but for now I'd say use the above patch if it's holding you back from upgrading EE versions.

Thanks,
Erik
