### ISSUE TITLE
Cache is not resetting

### ISSUE THREAD

**Issue by chadclark** [focuslabllc/dev_docs.ee_addon#8]
Hi there,

Using the dev branch (v 0.5.1), it seems as though I am having some cache issues. After updating and saving a Markdown document, reloading that page in Dev Docs does not reflect the change. I have to manually delete the content in the 'exp_dd_doc_sections' table to have it recognize the changes.

Am I overlooking something on my end? Thanks! It's a fantastic and useful add-on.

**Comment by erikreagan** [comment]
Hey @chadclark, 

Is your markdown document a single file or is it a directory that's being parsed/used?

Erik

**Comment by chadclark** [comment]
It is a directory with individual .md files.

**Comment by erikreagan** [comment]
Ah okay. That's a known issue with directories. The caching mechanism didn't exist at of 0.5.1.

This won't be great for performance, but if you really **need** a fix until the 1.0 release you can open up `mcp.dev_docs.php` and comment out the following lines: 94-99 and 102

**Comment by chadclark** [comment]
Ah, good to know. Thank you! If I was to do just one .md file, would that resolve the issue?

**Comment by erikreagan** [comment]
Yes, caching works as expected with a single file.

**Comment by chadclark** [comment]
Perfect. Thanks so much! It's a great add-on.
